### ISSUE TITLE
Guest user should be able to suggest a measure via email form

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/tracing-resilience#10]
Fields per Katie & Brianne 5/19

- name
- email
- organization
- full street address (at least city, state)
- name of measure
- reference for measure
- title
- description

**Comment by nathanstruhs** [comment]
@ybakos This is a guest submitting a measure, correct? Do you have any ideas for the best way to go about this?

I was thinking of simply adding a `:requires_approval` attribute to the Measure model. Which an admin could toggle.

**Comment by ybakos** [comment]
@nathanstruhs Yes, if we make this a model it should just be a Measure with a status / `approved` attribute.

**Comment by ybakos** [comment]
@nathanstruhs Let's see what they prefer.

**Comment by nathanstruhs** [comment]
@ybakos would the alternative to present to them be a separate model?

**Comment by ybakos** [comment]
It should be the same model if we imagine the use case (this isn't the truth, as we'd have to ask the client):

As an admin
Given someone has submitted a Measure requiring approval
When I view the details of the suggested Measure
I should see that the name, url, document, and title, and description are all complete and accurate
So that I can quickly approve it
And it's attributes are immediately valid for the system and other users

The benefit is that it requires a little diligence on the part of the submitter to complete everything as accurately as possible.

One drawback is that the diligence may prevent folks from being able to suggest measures that they know of but don't have the details for. This could also be beneficial, since folks can't just suggest stuff willy-nilly via a general text box.

It's a call that the client will have to make. Let me know if I am not understanding your questions or if I am unclear.

**Comment by ybakos** [comment]
@nathanstruhs See https://github.com/osu-cascades/tracing-resilience/commit/8ee126163dcb159f2fd23251b452395758032077
