### ISSUE TITLE
Deprecate Paperclip in lieu of Rails ActiveStorage

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/tracing-resilience#22]
Requires Rails 5.2.x.

See https://robots.thoughtbot.com/closing-the-trombone

Need to figure out how this works and how to handle `config.active_storage.service = :local` in production and what that should be set to.

**Comment by ybakos** [comment]
@nathanstruhs Why `beta1`? 5.2.0 full is out. 😄

**Comment by nathanstruhs** [comment]
Derp 🤷🏼‍♂️

**Comment by ybakos** [comment]
@nathanstruhs Just fyi, this wasn't an important issue to address. Better to have waited. 😄 

Changing the storage engine now doesn't deliver much client value - we've got things working just fine w/ pclip.

And, the main reason why it's not important is because the dependency being a rails upgrade. For minor version upgrades or higher (eg 5.1 -> 5.2 or 4.x - > 5.x) it takes some time because it's important to be methodical.

I'm just mentioning this so you're aware.

I've created [an issue to track the upgrade](https://github.com/osu-cascades/tracing-resilience/issues/27) and have assigned it to myself.

**Comment by ybakos** [comment]
Also see https://devcenter.heroku.com/articles/active-storage-on-heroku

@nathanstruhs I have already added the buildpacks for active_storage preview on Heroku. We may not need them at all, but having the buildpack installed suppresses a warning during deploy. Doesn't hurt anything. I think.

**Comment by ybakos** [comment]
@nathanstruhs I recommend focusing on this. Once this is done we can have the team upload measures.

**Comment by ybakos** [comment]
@nathanstruhs This one isn't complete - needs more configuration massaging.

On S3, we have a bucket, _osucascades_. That bucket contains one folder per app, eg:

- tracingresilience
- ecotoneweb
- beaverdamanalogues

Within those folders, is a subfolder for staging and production, eg:

- osucascades
-- tracingresilience
--- staging
--- production

Within which have been subfolders for each model and attachment, eg:

![screen shot 2018-05-29 at 2 05 27 pm](https://user-images.githubusercontent.com/5502/40685527-5d28ca8c-6349-11e8-9f4b-44aef1d15f2e.png)

I realize this is a means of organizing S3 storage that was paperclip-specific and worked well. I need to read the [docs about ActiveStorage](http://edgeguides.rubyonrails.org/active_storage_overview.html). My gut is telling me that we just create a specific bucket for the app.

(I would prefer not to if the config is simple, since all osu-cascades apps share one bucket.)

**Comment by ybakos** [comment]
Hmmm...
https://github.com/rails/rails/issues/32894
https://github.com/rails/rails/issues/32790

**Comment by ybakos** [comment]
Seems I'll need to make a dedicated bucket for this.
