### ISSUE TITLE
Models: Measure

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/tracing-resilience#7]
Attributes
- title
- tags (will implement later)
- document
- category - type enum:
  - general
  - individual
  - relational
  - community

**Comment by ybakos** [comment]
@nathanstruhs Clarified the domain language here. A "MeasurementTool" (aka survey aka pdf aka document) has a title, tags, attached file, and a category.

**Comment by ybakos** [comment]
I am not set on the "MeasurementTool" as a model name. Let's look at the docs / spreadsheet and understand the domain.

**Comment by nathanstruhs** [comment]
From the docs it seems that this model is most often referred to as 'Category of measure', Ill open this up in Campfire to see if we can get any further input.

**Comment by nathanstruhs** [comment]
@ybakos What do you think about just calling the model 'Measure', then we could have an attribute of catergory with a type of enum [:general, :individual, :relational, :community]

**Comment by ybakos** [comment]
@nathanstruhs Yep, good choice.

**Comment by nathanstruhs** [comment]
@ybakos do we want a relationship between the user and the measure? Is this a question for Meah/Katie/Brianne?

**Comment by ybakos** [comment]
@nathanstruhs I don't believe so. What did you have in mind regarding the meaning of the user-measure relationship?

**Comment by nathanstruhs** [comment]
@ybakos just the ability to organize measures by the user that uploads them. It seems like the main way to look up measures is by category or tag though.

**Comment by ybakos** [comment]
@nathanstruhs Let's not create that association right now.
